### ISSUE TITLE
Document shader compilation steps

### ISSUE THREAD

**Issue by xla** [cloudhead/rgx#11]
Likely done with `glslc` but it would be good to document or even have a command/script to regenrate the spirv of the shaders. As an example while working on the shape2d pipeline I used this command for the vertex shader:

```
glslc -Werror -o src/kit/data/shape.vert.spv  src/kit/data/shape.vert
```

**Comment by rbisewski** [comment]
@xla Maybe something like adding [this section in the readme](https://github.com/rbisewski/rgx/commit/e382ed64d00a35d2f6b19c271fad03272ebf87b4) in a branch I made. Or did you have something else in mind?

@cloudhead I could always add a bash script (or something along those lines) to build the shaders, assuming you would find that useful?

**Comment by cloudhead** [comment]
Good idea - I think for now a simple example of how to build a spir-v shader from a glsl shader is enough though, as in @xla 's example. That is pretty much also the command I used to build the existing ones. Later maybe it's possible to create a `build.rs` script or something which gets run when `cargo build` is called.

**Comment by rbisewski** [comment]
Sure, I'll make a pull request with the branch that has the individual commands documented in a few minutes...
