### ISSUE TITLE
Add a Changelog

### ISSUE THREAD

**Issue by dhardy** [cloudhead/rgx#15]
What changed in version 0.2.0? Adding a changelog would be very nice.

**Comment by dhardy** [comment]
To answer my own question:

- pipelines are no longer parameterised by size
- replace `rend.submit(frame)` with `rend.present(frame)`
- now call the following on a new frame:

     ```rust
    rend.update_pipeline(&self.pipeline, kit::ortho(out.width, out.height), &mut frame);
    ```

**Comment by cloudhead** [comment]
Yeah, also:

* `rend.prepare` renamed to `rend.submit`

**Comment by dhardy** [comment]
.... and we have version 0.3 out (`wgpu 0.4` support :tada:)

Close if you like, but the addition of a changelog would be nice.

**Comment by cloudhead** [comment]
Yep! I will keep it open as a reminder.

**Comment by cloudhead** [comment]
Here we go https://github.com/cloudhead/rgx/blob/master/CHANGELOG.md

**Comment by dhardy** [comment]
Aha, that's one way of doing it (but looks quite a lot of work). For the rand project we use the [keepachangelog](https://keepachangelog.com/en/1.0.0/) style and now make a habit of adding changelog entries within each PR.

**Comment by cloudhead** [comment]
Interesting.. 

Well, it's not so much work since I just take the git log and remove irrelevant entries. For libraries I think this mostly works, but having it as a process within PRs is a great idea.
