### ISSUE TITLE
docs.rs doesn't contain core module documentation anymore

### ISSUE THREAD

**Issue by ecton** [cloudhead/rgx#20]
It looks like the switch to put the renderer in its own feature flag caused the documentation for the core module to be omitted from docs.rs:

https://docs.rs/rgx/0.8.1/rgx/

compared to:

https://docs.rs/rgx/0.6.0/rgx/

I'm a bit new to publishing crates myself, and my quick google-fu failed me, so I'm putting in this issue in hopes someone with more know-how can submit a PR.

**Comment by Moar-Chan** [comment]
I had the same issue, seem you need to enable the renderer feature

example: rgx = {version = "0.8.1", features=["renderer"]}

**Comment by Moar-Chan** [comment]
Ah understood

**Comment by cloudhead** [comment]
Merged, thanks!
