### ISSUE TITLE
shape2d::Pipeline::resize is broken

### ISSUE THREAD

**Issue by dhardy** [cloudhead/rgx#9]
This method is clearly broken (try resizing one of the example windows like shapes, then replace `pip.resize(..)` with `pip = r.pipeline(w, h, Blending::default());` and compare).

My guess is that the new `ortho` matrix needs to be copied into `buf`, but I may be wrong.

https://github.com/cloudhead/rgx/blob/a3d3a37f638df1a9d44fd4c3a2f90e07538a478b/src/kit/shape2d.rs#L107-L111

**Comment by cloudhead** [comment]
Perhaps it's a poor choice of name, but the `resize` methods only sets the size data which gets sent via the `Renderer::update_pipeline` method to the gpu. See [this](https://github.com/cloudhead/rgx/blob/master/examples/offscreen.rs#L233) example. Once you call the later method, the uniform buffer is updated

**Comment by dhardy** [comment]
Ah, thanks. This does leave several of the examples broken, however (all those supporting `Resize` except `offscreen` and `threaded`).

I guess the main thing is to fix examples and mention any gotchas in the docs rather than worry about the method name.

**Comment by cloudhead** [comment]
I've made some changes to the API which removes `Pipeline::resize` and should overall make things simpler / less confusing. See here: https://github.com/cloudhead/rgx/commit/7947acb0619db22360572cd2906af3fef038fc87

If you encounter any issues, let me know!

**Comment by dhardy** [comment]
Sure, that's one way to solve it. Purely documenting this and fixing examples may also have been enough :man_shrugging:

**Comment by cloudhead** [comment]
It was a bad API - after this change I was able to delete 60 lines of code on `rx` :tada:
